In [1]:
!python -m pip install numpy


[notice] A new release of pip available: 22.3.1 -> 23.1
[notice] To update, run: python.exe -m pip install --upgrade pip


In [2]:
import numpy as np

In [3]:
a = np.array([8,6,5])

In [4]:
print(a.shape)

(3,)


In [5]:

k = np.array([(3,8,4),(9,3,5),(11,15,17),(19,31,8)])
print(k)
print(k.shape)

[[ 3  8  4]
 [ 9  3  5]
 [11 15 17]
 [19 31  8]]
(4, 3)


In [6]:
m = np.array([[[4,41],[8,81],[7,71]],[[3,31],[1,11],[5,51]],[[6,61],[9,91],[13,131]]])
print(m)
print(m.shape)

[[[  4  41]
  [  8  81]
  [  7  71]]

 [[  3  31]
  [  1  11]
  [  5  51]]

 [[  6  61]
  [  9  91]
  [ 13 131]]]
(3, 3, 2)


In [7]:
print(k[0:5:1 , 2])

[ 4  5 17  8]


In [8]:
print(k[:,-1].shape)

(4,)


In [9]:
print(k[:,-1:])

[[ 4]
 [ 5]
 [17]
 [ 8]]


In [10]:
print(m[1:,1:,:1])

[[[ 1]
  [ 5]]

 [[ 9]
  [13]]]


In [11]:
#print(m[])

In [12]:
print(k+5)

[[ 8 13  9]
 [14  8 10]
 [16 20 22]
 [24 36 13]]


In [13]:
print(k*5)

[[ 15  40  20]
 [ 45  15  25]
 [ 55  75  85]
 [ 95 155  40]]


In [14]:
k[:,1] = [30,33,37,88]
print(k)

[[ 3 30  4]
 [ 9 33  5]
 [11 37 17]
 [19 88  8]]


In [15]:
k[0,:]=[30,40,80]

In [16]:
print(k)

[[30 40 80]
 [ 9 33  5]
 [11 37 17]
 [19 88  8]]


In [17]:
k[:2,1:]= [[22,3454],[54,24]]
print(k)

[[  30   22 3454]
 [   9   54   24]
 [  11   37   17]
 [  19   88    8]]


In [18]:
#k[4,:] = [1,2,2]
#function se add karenge

np.append(k,[[1,1,1]], axis=0) #Zero to add new row


array([[  30,   22, 3454],
       [   9,   54,   24],
       [  11,   37,   17],
       [  19,   88,    8],
       [   1,    1,    1]])

In [19]:
k=np.append(k,[[1],[1],[1],[2]], axis=1)
print(k)

[[  30   22 3454    1]
 [   9   54   24    1]
 [  11   37   17    1]
 [  19   88    8    2]]


In [20]:
np.delete(k,1,1)

array([[  30, 3454,    1],
       [   9,   24,    1],
       [  11,   17,    1],
       [  19,    8,    2]])

In [21]:
np.delete(k , 1, axis=0)

array([[  30,   22, 3454,    1],
       [  11,   37,   17,    1],
       [  19,   88,    8,    2]])

In [22]:
k.reshape(2,8)

array([[  30,   22, 3454,    1,    9,   54,   24,    1],
       [  11,   37,   17,    1,   19,   88,    8,    2]])

In [23]:
print(k.shape)

(4, 4)


In [24]:
k.astype('uint16')

array([[  30,   22, 3454,    1],
       [   9,   54,   24,    1],
       [  11,   37,   17,    1],
       [  19,   88,    8,    2]], dtype=uint16)

In [25]:
k.astype(float)

array([[3.000e+01, 2.200e+01, 3.454e+03, 1.000e+00],
       [9.000e+00, 5.400e+01, 2.400e+01, 1.000e+00],
       [1.100e+01, 3.700e+01, 1.700e+01, 1.000e+00],
       [1.900e+01, 8.800e+01, 8.000e+00, 2.000e+00]])

In [26]:
k.mean()

236.125

In [27]:
k.std()

831.1493454097164

In [29]:
np.ones((2,3))

array([[1., 1., 1.],
       [1., 1., 1.]])

In [31]:
np.zeros((2,3) , dtype= int)

array([[0, 0, 0],
       [0, 0, 0]])

In [37]:
np.arange(1,11,2.5)

array([1. , 3.5, 6. , 8.5])

In [35]:
np.linspace(1,10,10)

array([ 1.,  2.,  3.,  4.,  5.,  6.,  7.,  8.,  9., 10.])

In [36]:
list(range(1,11,1))

[1, 2, 3, 4, 5, 6, 7, 8, 9, 10]

In [38]:
'''Range me sirf integer parameters aayenge. Arange me int float dono aaskte hai'''

'Range me sirf integer parameters aayenge. Arange me int float dono aaskte hai'

In [46]:
np.random.randint(1,6,[4,3,2])

array([[[3, 5],
        [2, 4],
        [5, 5]],

       [[5, 4],
        [3, 3],
        [4, 1]],

       [[3, 2],
        [1, 5],
        [4, 4]],

       [[1, 4],
        [3, 3],
        [2, 1]]])

In [47]:
np.random.randint(1,22)

15

In [48]:
np.random.randint(2,23,4)

array([ 7,  9, 17, 11])

In [52]:
np.random.seed(10)
np.random.randint(1,23,3)

array([10,  5, 16])

In [55]:
np.random.rand(3,4)  #generates no. less than 0

array([[0.81262096, 0.61252607, 0.72175532, 0.29187607],
       [0.91777412, 0.71457578, 0.54254437, 0.14217005],
       [0.37334076, 0.67413362, 0.44183317, 0.43401399]])

In [57]:
np.loadtxt('file.txt' , dtype=str)

array(['file', 'outside', 'python.'], dtype='<U7')

In [58]:
np.loadtxt('numberdata.txt')

array([[12.,  2.,  3., 33.],
       [22., 32., 22., 22.]])

In [61]:
p= np.random.rand(3,4)
p

array([[0.61776698, 0.51313824, 0.65039718, 0.60103895],
       [0.8052232 , 0.52164715, 0.90864888, 0.31923609],
       [0.09045935, 0.30070006, 0.11398436, 0.82868133]])

In [63]:
np.savetxt('new.txt' , p , delimiter= ' ; ')